# -*- coding: utf-8 -*-
"""test python script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p0RiIm3GXPbz887GmRnfZRTRj1aXYAXs
"""

# Function to separate even and odd numbers
def separate_even_odd(numbers):
    even_numbers = []
    odd_numbers = []

    # Iterate through the list and separate the numbers
    for number in numbers:
        if number % 2 == 0:
            even_numbers.append(number)
        else:
            odd_numbers.append(number)

    return even_numbers, odd_numbers

# Sample list of numbers
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Separate the numbers
evens, odds = separate_even_odd(numbers)

# Print the results
print("Even numbers:", evens)
print("Odd numbers:", odds)